-- AlterTable
ALTER TABLE "address" ALTER COLUMN "street" DROP NOT NULL,
ALTER COLUMN "zip_code" DROP NOT NULL,
ALTER COLUMN "district" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL;

-- AlterTable
ALTER TABLE "calls" ALTER COLUMN "start" DROP NOT NULL,
ALTER COLUMN "end" DROP NOT NULL,
ALTER COLUMN "contact_channel" DROP NOT NULL;

-- AlterTable
ALTER TABLE "clients" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "cnpjcpf" DROP NOT NULL,
ALTER COLUMN "nationality" DROP NOT NULL,
ALTER COLUMN "born_in" DROP NOT NULL,
ALTER COLUMN "telephone" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL;
